import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { WalletProvider } from '@solana/wallet-adapter-react'
import { SolWallet } from '../context/SolWallet'
import { UIProvider } from '@/context/UIProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SolWallet>
          <UIProvider>
            
            {children}
          </UIProvider>
        </SolWallet>
      </body>

    </html>
  )
}
